"use client";

import { useEffect } from "react";
import { usePathname } from "next/navigation";

// Text-only localization keeps the Spanish routes on the same tested component
// tree as English while translating every visible label after hydration.
const translations: Record<string, string> = {
  "Peruvian origin.": "Origen peruano.", "Global opportunities.": "Oportunidades globales.",
  "Peruvian Origin": "Origen peruano", "explore fresh fruit": "explorar fruta fresca", "explore iqf": "explorar IQF", "explore maquila": "explorar maquila", "EXPLORE FRESH FRUIT": "EXPLORAR FRUTA FRESCA", "EXPLORE IQF": "EXPLORAR IQF", "EXPLORE MAQUILA": "EXPLORAR MAQUILA",
  "Fresh. Frozen. Processed.": "Fresco. Congelado. Procesado.",
  "Premium Quality": "Calidad premium", "Integrated Solutions": "Soluciones integrales", "Fresh, Frozen & Processing": "Fresco, congelado y procesado", "Global Supply": "Abastecimiento global", "USA, Europe & Beyond": "EE. UU., Europa y más",
  "What are you": "¿Qué estás", "looking for?": "buscando?", "Three solutions. One partner.": "Tres soluciones. Un solo socio.",
  "Our solutions": "Nuestras soluciones", "Fresh Fruit": "Fruta fresca", "Peruvian fresh fruit for international markets.": "Fruta fresca peruana para mercados internacionales.", "Explore fresh fruit": "Explorar fruta fresca", "IQF Frozen Fruit": "Fruta congelada IQF", "Frozen fruit solutions for USA & Europe.": "Soluciones de fruta congelada para EE. UU. y Europa.", "Explore IQF": "Explorar IQF", "Maquila Services": "Servicios de maquila", "Processing and packing solutions for your business.": "Soluciones de procesamiento y empaque para tu negocio.", "Explore maquila": "Explorar maquila",
  "From Peru to the world": "Del Perú al mundo", "Our fresh & frozen": "Nuestros productos frescos y congelados", "Quality products, grown and processed in Peru.": "Productos de calidad, cultivados y procesados en el Perú.",
  "Quality Assured": "Calidad garantizada", "Strict quality control at every step.": "Estricto control de calidad en cada etapa.", "SENASA Authorized": "Autorizado por SENASA", "Authorized primary-processing facility.": "Planta autorizada para procesamiento primario.", "Food Safety": "Seguridad alimentaria", "International food safety standards and traceability systems.": "Estándares internacionales de seguridad alimentaria y sistemas de trazabilidad.", "Sustainable": "Sostenible", "Committed to responsible agriculture and the environment.": "Comprometidos con la agricultura responsable y el medio ambiente.", "Global Expertise": "Experiencia global", "Experience in international markets and reliable supply chain.": "Experiencia en mercados internacionales y una cadena de suministro confiable.",
  "Our facility": "Nuestra planta", "The infrastructure that supports our supply.": "La infraestructura que respalda nuestro abastecimiento.", "From reception and selection to packaging and primary processing, our own facilities give us greater control over product handling, quality, and operational flexibility.": "Desde la recepción y selección hasta el empaque y procesamiento primario, nuestras instalaciones nos dan mayor control sobre el manejo, la calidad y la flexibilidad operativa.", "DISCOVER OUR FACILITY": "DESCUBRIR NUESTRA PLANTA",
  "Your trust, our commitment": "Tu confianza, nuestro compromiso", "SENASA Authorized Facility": "Planta autorizada por SENASA", "We are authorized by SENASA for the primary processing of agricultural foods of plant origin.": "Estamos autorizados por SENASA para el procesamiento primario de alimentos agrícolas de origen vegetal.", "Authorization No.": "N.º de autorización", "VIEW AUTHORIZATION DOCUMENT": "VER DOCUMENTO DE AUTORIZACIÓN",
  "Contact Titan Fruit": "Contacta a Titan Fruit", "Let's start a conversation.": "Comencemos una conversación.", "Tell us what you need and our team will help you find the right fresh, frozen or processing solution.": "Cuéntanos qué necesitas y nuestro equipo te ayudará a encontrar la solución fresca, congelada o de procesamiento adecuada.", "We are here to help.": "Estamos aquí para ayudarte.", "Leave your details and we will get back to you shortly.": "Déjanos tus datos y te responderemos pronto.", "Location": "Ubicación", "Email": "Correo electrónico", "Phone": "Teléfono", "Send us a message": "Envíanos un mensaje", "How can we help?": "¿Cómo podemos ayudarte?", "Share a few details about your project. A Titan Fruit specialist will reply to you soon.": "Comparte algunos detalles sobre tu proyecto. Un especialista de Titan Fruit te responderá pronto.", "Name": "Nombre", "Company": "Empresa", "Message": "Mensaje", "Your name": "Tu nombre", "Your company": "Tu empresa", "Tell us about your requirements...": "Cuéntanos sobre tus necesidades...", "Send message": "Enviar mensaje", "Your message will be addressed to ventas@titanfruitperu.com.": "Tu mensaje será enviado a ventas@titanfruitperu.com.", "Ready to grow together?": "¿Listos para crecer juntos?", "Get in touch": "Contáctanos",
  "About us": "Nosotros", "Our experience today allows us to export more Peruvian fruits in fresh and frozen formats.": "Nuestra experiencia nos permite exportar más frutas peruanas en formatos frescos y congelados.", "Who we are": "Quiénes somos", "We are Titan Fruit": "Somos Titan Fruit", "A Peruvian agro-export company that pioneered dragon fruit exports—among Peru's first fresh dragon fruit exporters in 2023 and 2024—and today brings that experience to more fruits for the world: avocado, blueberry, strawberry and dragon fruit, fresh and frozen.": "Empresa peruana agroexportadora que lideró la exportación de pitahaya —entre las primeras del Perú en pitahaya fresca en 2023 y 2024— y hoy convierte esa experiencia en más frutas para el mundo: palta, arándano, fresa y pitahaya, frescas y congeladas.", "From the field to your hands.": "Del campo a tus manos.", "With our own crops and specialized packing operations, we maintain control over product quality from origin to final destination.": "Con cultivos propios y operaciones de empaque especializadas, mantenemos el control de la calidad desde el origen hasta el destino final.", "What we do": "Qué hacemos", "We grow, process and export fruit of the highest quality.": "Cultivamos, procesamos y exportamos fruta de la más alta calidad.", "Our products": "Nuestros productos", "Our infrastructure": "Nuestra infraestructura", "Where we operate": "Dónde operamos", "We bring the best of Peru to the world.": "Llevamos lo mejor del Perú al mundo.", "We export to demanding markets in the USA and Europe, as well as North America, Asia, the Middle East and Latin America, always meeting international standards.": "Exportamos a mercados exigentes de EE. UU. y Europa, así como de Norteamérica, Asia, Medio Oriente y Latinoamérica, cumpliendo siempre los estándares internacionales.", "Why work with Titan Fruit?": "¿Por qué trabajar con Titan Fruit?", "A trusted partner for your business.": "Un socio confiable para tu negocio.", "Sustainability": "Sostenibilidad", "Strong roots, a bright future.": "Raíces firmes, un futuro brillante.", "We believe in a healthier future through better food.": "Creemos en un futuro más saludable a través de una mejor alimentación.",
  "IQF frozen fruit solutions": "Soluciones de fruta congelada IQF", "IQF Frozen": "Congelado IQF", "Fruit from Peru": "Fruta del Perú", "Individually quick frozen to lock in freshness, flavor, color and nutrients.": "Congelado individualmente para conservar frescura, sabor, color y nutrientes.", "VIEW PRODUCTS": "VER PRODUCTOS", "Our IQF frozen fruits": "Nuestras frutas congeladas IQF", "Premium Peruvian fruits, IQF to perfection.": "Frutas peruanas premium, congeladas IQF a la perfección.", "Consistent quality, reliable supply and versatile formats for your business.": "Calidad constante, abastecimiento confiable y formatos versátiles para tu negocio.", "Applications": "Aplicaciones", "View details": "Ver detalles", "Why choose Titan Fruit IQ?": "¿Por qué elegir Titan Fruit IQF?", "Built for quality and consistency.": "Diseñado para calidad y consistencia.", "Where we serve": "Dónde atendemos", "Looking for a specific product": "¿Buscas un producto específico?", "Or custom solution?": "¿O una solución personalizada?", "REQUEST IQF QUOTE": "SOLICITAR COTIZACIÓN IQF", "Download brochure": "Descargar folleto",
  "Official documentation": "Documentación oficial", "SENASA health authorization": "Autorización sanitaria SENASA", "View certificate": "Ver certificado", "Opens the official PDF in a new tab.": "Abre el PDF oficial en una nueva pestaña.", "Our promise": "Nuestro compromiso", "Committed to quality and the future.": "Comprometidos con la calidad y el futuro.",
  "Infrastructure that delivers quality": "Infraestructura que entrega calidad", "Each area of our plant is designed to ensure the safety, traceability and quality of the fruit that reaches the world.": "Cada área de nuestra planta está diseñada para garantizar la seguridad, trazabilidad y calidad de la fruta que llega al mundo.", "Our facilities": "Nuestras instalaciones", "Exterior": "Exterior", "Reception": "Recepción", "Selection": "Selección", "Processing": "Procesamiento", "Packing": "Empaque", "Cold storage": "Almacenamiento en frío", "Quality control": "Control de calidad", "Dispatch": "Despacho", "From origin to export": "Del origen a la exportación", "Farm / suppliers": "Campo / proveedores", "International logistics": "Logística internacional", "Customer": "Cliente", "An integrated and controlled process that guarantees safe, high-quality fruit, ready for the most demanding markets.": "Un proceso integrado y controlado que garantiza fruta segura y de alta calidad, lista para los mercados más exigentes.", "Built-up area": "Área construida", "Authorized for primary processing": "Autorizado para procesamiento primario", "Food quality and safety standards": "Estándares de calidad e inocuidad alimentaria", "Skilled professionals committed to quality": "Profesionales capacitados comprometidos con la calidad.",
  "Processing partnership": "Alianza de procesamiento", "Flexible processing.": "Procesamiento flexible.", "A trusted partner.": "Un socio confiable.", "Processing solutions designed around your business needs.": "Soluciones de procesamiento diseñadas para las necesidades de tu negocio.", "Authorized Facility": "Planta autorizada", "Global Perspective": "Perspectiva global", "Primary processing takes place in our SENASA-authorized facility.": "El procesamiento primario se realiza en nuestra planta autorizada por SENASA.", "Built for international B2B supply requirements.": "Diseñada para las necesidades internacionales de suministro B2B.",
  "Peruvian fresh produce": "Productos frescos peruanos", "Featured products": "Productos destacados", "From our fields": "Desde nuestros campos", "Availability": "Disponibilidad", "Looking for a specific product?": "¿Buscas un producto específico?", "ASK ABOUT AVAILABILITY": "CONSULTAR DISPONIBILIDAD",
  "Fresh & Agricultural": "Frutas y productos agrícolas", "Agricultural": "agrícolas", "Premium fresh fruits and vegetables from Peru, carefully selected and processed in our SENASA-authorized facility to meet global standards.": "Frutas y verduras frescas premium del Perú, cuidadosamente seleccionadas y procesadas en nuestra planta autorizada por SENASA para cumplir los estándares globales.", "Fruits": "Frutas", "Vegetables": "Verduras", "OTHER SELECTED FRUITS": "OTRAS FRUTAS SELECCIONADAS", "OTHER SELECTED VEGETABLES": "OTRAS VERDURAS SELECCIONADAS", "SHOW LESS": "MOSTRAR MENOS",
  "Global supply": "Abastecimiento global", "Peru connected to key markets.": "Perú conectado con mercados clave.", "Pause globe": "Pausar planeta", "Resume globe": "Reanudar planeta", "Peru origin": "Origen: Perú", "United States & Europe": "Estados Unidos y Europa", "Drag to rotate and zoom, or use the button to pause the automatic rotation.": "Arrastra para girar y acercar, o usa el botón para pausar la rotación automática.", "Europe": "Europa", "United States": "Estados Unidos", "North America": "Norteamérica", "Middle East": "Medio Oriente", "Latin America": "Latinoamérica",
  "EXPLORE OUR PRODUCTS": "EXPLORAR NUESTROS PRODUCTOS", "Global Markets": "Mercados globales", "Supplying fresh produce to Europe and beyond.": "Abastecemos productos frescos a Europa y más allá.", "IQF technology": "Tecnología IQF", "Individually quick frozen": "Congelado individualmente", "Reliable supply": "Abastecimiento confiable", "Year-round availability": "Disponibilidad todo el año", "Premium quality": "Calidad premium", "Strict quality control": "Estricto control de calidad", "Food safety": "Seguridad alimentaria", "SENASA-authorized facility": "Planta autorizada por SENASA",
  "Modern and secure facilities.": "Instalaciones modernas y seguras.", "Fruit reception and verification.": "Recepción y verificación de la fruta.", "Manual selection to ensure quality.": "Selección manual para garantizar la calidad.", "Efficient processes with the right equipment.": "Procesos eficientes con el equipo adecuado.", "Careful packing to protect the fruit.": "Empaque cuidadoso para proteger la fruta.", "Optimal preservation in controlled environments.": "Conservación óptima en ambientes controlados.", "Analysis and controls at every stage of the process.": "Análisis y controles en cada etapa del proceso.", "Preparation and dispatch for export.": "Preparación y despacho para exportación.",
  "Authorized facility for primary processing.": "Planta autorizada para procesamiento primario.", "Traceability by lot from origin to destination.": "Trazabilidad por lote desde el origen hasta el destino.", "Quality inspection throughout the process.": "Inspección de calidad durante todo el proceso.", "Precise temperature handling and preservation.": "Control y conservación precisa de la temperatura.", "Safe and responsible processes.": "Procesos seguros y responsables.", "Aligned with national and international standards.": "Alineados con estándares nacionales e internacionales.", "Trained, committed professionals.": "Profesionales capacitados y comprometidos.", "We optimize every stage to deliver better.": "Optimizamos cada etapa para entregar lo mejor.",
  "We are an integrated partner for fresh fruit, IQF frozen solutions and processing services. From the field to global markets, we deliver quality, reliability and trust.": "Somos un socio integral para fruta fresca, soluciones congeladas IQF y servicios de procesamiento. Del campo a los mercados globales, entregamos calidad, confiabilidad y confianza.", "International partnerships": "Alianzas internacionales", "We serve global markets": "Atendemos mercados globales", "Peruvian quality, delivered worldwide.": "Calidad peruana, entregada en todo el mundo.", "Reliable IQF frozen fruit supply for the USA, serving food manufacturers, distributors and foodservice.": "Abastecimiento confiable de fruta congelada IQF para EE. UU., fabricantes de alimentos, distribuidores y servicios de alimentación.", "Premium fresh and frozen fruit supplier for Europe, meeting the highest quality and food safety requirements.": "Proveedor de frutas frescas y congeladas premium para Europa, cumpliendo los más altos requisitos de calidad e inocuidad alimentaria.", "Certified processes and controls at every step.": "Procesos certificados y controles en cada etapa.", "Consistent supply throughout the year.": "Abastecimiento constante durante todo el año.", "Responsible practices with local growers.": "Prácticas responsables con agricultores locales.", "Modern facilities and specialized technology.": "Instalaciones modernas y tecnología especializada.", "Knowledge of international requirements.": "Conocimiento de los requisitos internacionales.", "Solutions adapted to every customer.": "Soluciones adaptadas a cada cliente.",
  "Individually quick frozen to preserve natural quality, color, flavor and nutrients.": "Congelado individualmente para conservar la calidad natural, el color, el sabor y los nutrientes.", "Strict quality control from raw fruit selection to final packaging.": "Estricto control de calidad desde la selección de la fruta hasta el empaque final.", "SENASA-authorized facility with international food safety standards.": "Planta autorizada por SENASA con estándares internacionales de seguridad alimentaria.", "Custom packing options to meet your market and brand needs.": "Opciones de empaque personalizadas para las necesidades de tu mercado y marca.", "Reliable supply for the USA, Europe and other international markets.": "Abastecimiento confiable para EE. UU., Europa y otros mercados internacionales.", "Primary processing of agricultural products of plant origin.": "Procesamiento primario de productos agrícolas de origen vegetal.", "From origin to final destination.": "Desde el origen hasta el destino final.", "Years of experience in fruit processing and export.": "Años de experiencia en procesamiento y exportación de frutas.",
  "Our own packing and primary processing facility is designed to ensure efficiency, food safety and the highest quality standards in every step of the process.": "Nuestra planta propia de empaque y procesamiento primario está diseñada para garantizar eficiencia, seguridad alimentaria y los más altos estándares de calidad en cada etapa del proceso.", "Own facility": "Planta propia", "SENASA authorized": "Autorizado por SENASA", "Primary Processing": "Procesamiento primario", "Farm / Suppliers": "Campo / proveedores", "Quality Control": "Control de calidad", "Cold Storage": "Almacenamiento en frío", "Hass Avocado": "Palta Hass", "Dragon Fruit": "Pitahaya", "Blueberries": "Arándanos", "Strawberries": "Fresas", "Passion Fruit": "Maracuyá", "Selected Fruit": "Fruta seleccionada", "Selected Vegetable": "Verdura seleccionada", "Guacamole & dips": "Guacamole y salsas", "Smoothies": "Batidos", "Foodservice": "Servicio de alimentos", "Food manufacturing": "Fabricación de alimentos", "Smoothies & juices": "Batidos y jugos", "Beverages": "Bebidas", "Desserts": "Postres", "Bakery": "Panadería", "Yogurt & dairy": "Yogur y lácteos", "Ice cream & dairy": "Helados y lácteos", "Product details pending confirmation.": "Detalles del producto pendientes de confirmación.", "REQUEST A QUOTE": "SOLICITAR COTIZACIÓN",
  "Guaranteed quality": "Calidad garantizada", "Sustainable production": "Producción sostenible", "Export expertise": "Experiencia exportadora", "Personal support": "Soporte personalizado", "We promote the development of responsible local growers by strengthening long-term partnerships, continuous training and support so that every fruit reaches the world with the highest quality.": "Impulsamos el desarrollo de agricultores locales responsables mediante alianzas a largo plazo, capacitación continua y apoyo para que cada fruta llegue al mundo con la más alta calidad.", "IQF Frozen Avocado": "Palta congelada IQF", "IQF Frozen Dragon Fruit (American Beauty)": "Pitahaya congelada IQF (American Beauty)", "IQF Frozen Blueberries": "Arándanos congelados IQF", "IQF Frozen Strawberries": "Fresas congeladas IQF", "Creamy texture and natural flavor, perfect for guacamole, dips, smoothies and foodservice.": "Textura cremosa y sabor natural, perfectos para guacamole, salsas, batidos y servicio de alimentos.", "Vibrant color and exotic flavor, ideal for smoothies, beverages, desserts and more.": "Color vibrante y sabor exótico, ideales para batidos, bebidas, postres y más.", "Bursting with flavor and antioxidants, perfect for a wide range of food applications.": "Ricos en sabor y antioxidantes, perfectos para una amplia variedad de aplicaciones alimentarias.", "Sweet, juicy and convenient. Perfect for desserts, smoothies, bakery and more.": "Dulces, jugosas y prácticas. Perfectas para postres, batidos, panadería y más.", "Supplying high-quality IQF frozen fruit to the global food industry.": "Abastecemos fruta congelada IQF de alta calidad a la industria alimentaria mundial.", "Trusted IQF frozen fruit exporter to the USA, serving food manufacturers, distributors, foodservice and retail.": "Exportador confiable de fruta congelada IQF a EE. UU., para fabricantes de alimentos, distribuidores, servicios de alimentación y retail.", "Reliable IQF frozen fruit supplier for Europe, meeting the highest quality and food safety requirements.": "Proveedor confiable de fruta congelada IQF para Europa, cumpliendo los más altos requisitos de calidad e inocuidad alimentaria.",
};

const spanishRoutes: Record<string, string> = {
  "/en": "/es", "/en/fresh-fruit": "/es/fruta-fresca", "/en/iqf-frozen": "/es/iqf-congelados",
  "/en/maquila-services": "/es/servicios-maquila", "/en/our-facility": "/es/nuestra-planta",
  "/en/about-us": "/es/nosotros", "/en/quality-certifications": "/es/calidad-certificaciones", "/en/contact": "/es/contacto",
};

export function SpanishTranslator() {
  const pathname = usePathname();

  useEffect(() => {
    let frame = 0;
    const translate = () => {
      const roots = Array.from(document.querySelectorAll("main"));
      for (const root of roots) {
        root.querySelectorAll<HTMLAnchorElement>('a[href^="/en"]').forEach((anchor) => {
          const url = new URL(anchor.getAttribute("href") || "/en", window.location.origin);
          const base = Object.keys(spanishRoutes).sort((a, b) => b.length - a.length).find((route) => url.pathname === route || url.pathname.startsWith(`${route}/`));
          if (base) anchor.setAttribute("href", `${spanishRoutes[base]}${url.pathname.slice(base.length)}${url.search}${url.hash}`);
        });
        const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
        const nodes: Text[] = [];
        let node: Node | null;
        while ((node = walker.nextNode())) nodes.push(node as Text);
        for (const textNode of nodes) {
          if (textNode.parentElement?.closest("script,style")) continue;
          let value = textNode.nodeValue || "";
          if (value.trim().toLowerCase() === "products") { textNode.nodeValue = ""; continue; }
          for (const [english, spanish] of Object.entries(translations)) value = value.split(english).join(spanish);
          if (value !== textNode.nodeValue) textNode.nodeValue = value;
        }
      }
      document.documentElement.lang = "es";
    };
    const schedule = () => {
      cancelAnimationFrame(frame);
      frame = requestAnimationFrame(translate);
    };
    schedule();
    const observer = new MutationObserver(schedule);
    observer.observe(document.body, { subtree: true, childList: true, characterData: true });
    const delayed = window.setTimeout(schedule, 100);
    return () => { cancelAnimationFrame(frame); window.clearTimeout(delayed); observer.disconnect(); };
  }, [pathname]);
  return null;
}
