import type { Metadata } from "next";
import Image from "next/image";
import { HomeHero } from "@/components/hero/home-hero";
import { BusinessLineCard } from "@/components/business/business-line-card";
import { SectionHeading } from "@/components/ui/section-heading";
import { ProductShowcase } from "@/components/products/product-showcase";
import { TrustItems } from "@/components/trust/trust-items";
import { FacilitySection } from "@/components/facility/facility-section";
import { CertificationSection } from "@/components/trust/certification-section";
import { images } from "@/data/images";

export const metadata: Metadata = { title:"Peruvian origin. Global opportunities.", description:"Fresh fruit, IQF frozen solutions and processing services from Peru for international partners.", alternates:{ canonical:"/en", languages:{ en:"/en", es:"/es", "x-default":"/en" } }, openGraph:{ title:"Titan Fruit | Peruvian origin. Global opportunities.", description:"Fresh, frozen and processed solutions from Peru.", type:"website", url:"/en" } };
export default function EnglishHome() { const jsonLd = { "@context":"https://schema.org", "@graph":[{ "@type":"Organization", name:"Titan Fruit", url:"https://titanfruit.pe/en", description:"Integrated Peruvian partner for fresh fruit, IQF frozen solutions and processing services." }, { "@type":"WebSite", name:"Titan Fruit", url:"https://titanfruit.pe/en" }] }; return <main><HomeHero/><section className="container py-20 sm:py-28"><SectionHeading eyebrow="Our solutions" title={<>What are you<br/>looking for?</>} intro="Three solutions. One partner."/><div className="mt-10 grid gap-5 md:grid-cols-3"><BusinessLineCard icon="leaf" title="Fresh Fruit" description="Peruvian fresh fruit for international markets." image={images.fresh} href="/en/fresh-fruit" action="EXPLORE FRESH FRUIT"/><BusinessLineCard icon="snow" title="IQF Frozen Fruit" description="Frozen fruit solutions for USA & Europe." image={images.frozen} href="/en/iqf-frozen" action="EXPLORE IQF"/><BusinessLineCard icon="factory" title="Maquila Services" description="Processing and packing solutions for your business." image={images.maquila} href="/en/maquila-services" action="EXPLORE MAQUILA"/></div></section><section className="bg-cream py-20 sm:py-28"><div className="container"><SectionHeading eyebrow="From Peru to the world" title={<>Our fresh &amp; frozen<br/>products</>} intro="Quality products, grown and processed in Peru."/><div className="mt-10"><ProductShowcase/></div></div></section><section className="bg-[#f7f8f4] py-14 sm:py-16"><div className="container"><TrustItems/></div></section><FacilitySection image={images.facility}/><CertificationSection image={images.senasa}/><section className="container py-20 sm:py-28"><SectionHeading eyebrow="International partnerships" title={<>We serve global markets</>} intro="Peruvian quality, delivered worldwide."/><div className="mt-10 grid gap-5 md:grid-cols-2">{[["USA", "Reliable IQF frozen fruit supply for the USA, serving food manufacturers, distributors and foodservice.", images.usa], ["Europe", "Premium fresh and frozen fruit supplier for Europe, meeting the highest quality and food safety requirements.", images.europeLondon]].map(([title, text, image]) => <article key={title} className="image-zoom relative min-h-[340px] overflow-hidden rounded-4xl bg-forest text-white"><Image src={image} alt={`${title} global market`} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover opacity-70"/><div className="absolute inset-0 bg-gradient-to-t from-forest via-forest/35 to-transparent"/><div className="absolute bottom-0 p-7 sm:p-9"><h3 className="text-4xl font-bold tracking-[-.05em]">{title}</h3><p className="mt-3 max-w-md text-sm leading-6 text-white/80">{text}</p></div></article>)}</div></section><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}/></main>; }
