import type { Metadata } from "next";
import { PageHero } from "@/components/hero/page-hero";
import { SectionHeading } from "@/components/ui/section-heading";
import { ProductCategory } from "@/components/products/product-category";
import { products } from "@/data/products";
import { images } from "@/data/images";
import { Button } from "@/components/ui/button";
import { Icon, type IconName } from "@/components/ui/icons";

export const metadata: Metadata = { title:"Fresh & Agricultural Products", description:"Premium fresh fruits and vegetables from Peru, carefully selected and processed in our SENASA-authorized facility.", alternates:{ canonical:"/en/fresh-fruit", languages:{ en:"/en/fresh-fruit", es:"/es/fruta-fresca", "x-default":"/en/fresh-fruit" } }, openGraph:{ title:"Fresh & Agricultural Products | Titan Fruit", description:"Premium fresh fruits and vegetables from Peru.", url:"/en/fresh-fruit" } };
const bar: { icon: IconName; title: string; text: string }[] = [{ icon:"globe", title:"Global Markets", text:"Supplying fresh produce to Europe and beyond." }, { icon:"shield", title:"Premium Quality", text:"Strict selection and quality control at every step." }, { icon:"certificate", title:"SENASA Authorized", text:"Our facility is authorized for a wide range of products." }, { icon:"leaf", title:"Sustainable", text:"Committed to responsible agriculture and sustainability." }];
export default function FreshFruitPage() { const fruits = products.filter((p) => p.category === "fruit"); const vegetables = products.filter((p) => p.category === "vegetable"); return <main><PageHero eyebrow="Peruvian fresh produce" title={<>Fresh &amp; Agricultural<br/>Products</>} description="We export premium fresh fruits and vegetables from Peru, carefully selected and processed in our SENASA-authorized facility to meet global standards." image={images.freshFruitHero} fullScreen/><section id="products" className="container py-20 sm:py-28"><SectionHeading eyebrow="From our fields" title="Featured products" intro="A selected range of premium agricultural products from Peru."/><div className="mt-14 space-y-20"><ProductCategory title="Fruits" products={fruits} expandLabel="OTHER SELECTED FRUITS"/><ProductCategory title="Vegetables" products={vegetables} expandLabel="OTHER SELECTED VEGETABLES"/></div></section><section className="bg-cream py-16 sm:py-20"><div className="container flex flex-col items-start justify-between gap-8 rounded-4xl bg-lime px-7 py-10 sm:px-12 sm:py-12 lg:flex-row lg:items-center"><div><p className="eyebrow text-forest/70">Availability</p><h2 className="mt-3 text-3xl font-bold tracking-[-.05em] text-forest sm:text-4xl">Looking for a specific product?</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-forest/70">Our authorized processing facility covers a broad range of agricultural products.</p></div><Button href="#contact" tone="dark" className="shrink-0">ASK ABOUT AVAILABILITY</Button></div></section><section className="bg-forest text-white"><div className="container grid gap-7 py-14 sm:grid-cols-2 lg:grid-cols-4">{bar.map((item) => <article key={item.title} className="flex gap-3"><Icon name={item.icon} className="h-7 w-7 shrink-0 text-lime"/><div><h3 className="text-xs font-bold uppercase tracking-[.1em]">{item.title}</h3><p className="mt-2 text-sm leading-5 text-white/65">{item.text}</p></div></article>)}</div></section></main>; }
